import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { chromium } = require('C:/Users/Jay/Desktop/Bosom friend APP/node_modules/.pnpm/playwright-core@1.61.1/node_modules/playwright-core');
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on('pageerror', e => errors.push(String(e).slice(0, 140)));
await page.goto('http://127.0.0.1:3081/bosom-friend/', { waitUntil: 'networkidle', timeout: 60000 });
await page.waitForTimeout(9000);
console.log('title=' + await page.title());
const aside = await page.evaluate(() => { const el = document.querySelector('aside'); return el ? el.innerText : ''; });
console.log('addChannelBottom=' + aside.includes('添加频道'));
const navItems = await page.evaluate(() => { const nav = document.querySelector('[data-testid=sidebar-nav]'); return nav ? nav.innerText.split(String.fromCharCode(10)).filter(Boolean) : []; });
console.log('navItems=' + JSON.stringify(navItems));
await page.evaluate(() => { document.querySelector('[data-testid=sidebar-account-entry]').click(); }); await page.waitForTimeout(3500);
const modal = await page.evaluate(() => document.body.innerText);
console.log('modalMain=' + (modal.includes('我的频道') && modal.includes('刷新粉丝数') && modal.includes('新建分组')));
console.log('persistGroup=' + modal.includes('持久化素材组'));
console.log('pageerrors=' + errors.length);
for (const e of errors.slice(0, 4)) console.log('  PE: ' + e.split(String.fromCharCode(10))[0]);
await browser.close();