import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { chromium } = require('C:/Users/Jay/Desktop/Bosom friend APP/node_modules/.pnpm/playwright-core@1.61.1/node_modules/playwright-core');
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on('pageerror', e => errors.push(String(e).slice(0, 140)));
await page.goto('http://127.0.0.1:3081/bosom-friend/', { waitUntil: 'networkidle', timeout: 60000 });
await page.waitForTimeout(9000);
const navText = await page.evaluate(() => { const el = document.querySelector('aside'); return el ? el.innerText : ''; });
const order = ['内容创作', 'AI互动', '我的任务', '发布日历', '数据中心', '全局监控', '知识库'];
let okOrder = true; let last = -1;
for (const it of order) { const i = navText.indexOf(it); if (i <= last) { okOrder = false; console.log('ORDER FAIL: ' + it + ' idx=' + i); } last = i; }
console.log('navOrderOk=' + okOrder);
const hasEn = /[a-zA-Z]{3,}/.test(navText.replace('AI互动', '').replace('ID', '').replace('Bosom Friend', ''));
console.log('navHasEnglish=' + hasEn + ' (excluding AI/ID)');
await page.evaluate(() => { location.hash = '#/accounts'; }); await page.waitForTimeout(4000);
const accBody = await page.evaluate(() => document.body.innerText);
console.log('accountsHasPublishBtn=' + (accBody.includes('新建作品') || accBody.includes('一键发布')));
console.log('accountsHasAddChannel=' + (accBody.includes('添加频道') || accBody.includes('添加')));
await page.evaluate(() => { location.hash = '#/monitor'; }); await page.waitForTimeout(4500);
const monBody = await page.evaluate(() => document.body.innerText);
console.log('monitorStatsCards=' + (monBody.includes('绑定账号') && monBody.includes('在线账号') && monBody.includes('评论接待') && monBody.includes('私信接待')));
await page.evaluate(() => { location.hash = '#/data-statistics'; }); await page.waitForTimeout(4000);
console.log('statsPage=' + (await page.evaluate(() => document.body.innerText.length)));
await page.evaluate(() => { location.hash = '#/calendar'; }); await page.waitForTimeout(4000);
console.log('calendarPage=' + (await page.evaluate(() => document.body.innerText.length)));
await page.evaluate(() => { location.hash = '#/publish'; }); await page.waitForTimeout(3500);
console.log('publishRouteGone=' + ((await page.evaluate(() => location.hash)) === '#/' ? 'YES(navigate-home)' : 'NO'));
console.log('pageerrors=' + errors.length);
for (const e of errors.slice(0, 6)) console.log('  PE: ' + e.split(String.fromCharCode(10))[0]);
await browser.close();